name: Scrape Cloudflare Top IPs

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install beautifulsoup4 pandas
        pip install selenium webdriver_manager # 安装selenium和webdriver_manager

    # ====== 修改 Chrome 设置，移除单独的 ChromeDriver 设置 ======
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1 # 使用这个Action来安装Chrome
      with:
        chrome-version: 'stable' # 安装稳定版Chrome
    
    # 移除或注释掉 setup-chromedriver 步骤，让 webdriver_manager 处理
    # - name: Setup ChromeDriver
    #   uses: browser-actions/setup-chromedriver@v1
    #   with:
    #     chromedriver-version: 'stable'
    # ==============================================================

    - name: Run IP extraction script
      run: python extract_ips_selenium.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add data/*.csv
        git commit -m "Automated IP data update for $(date +%Y-%m-%d_%H-%M)" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
